### ISSUE TITLE
create a minimal omex file that is accepted on https://run.biosimulations.org/

### ISSUE THREAD

**Issue by stellaprins** [robertvi/SBMLShowcase#2]
Biosimulators requires an omex file as input, but it does not seem to accept the omex files we created. Why are the omex files not accepted? To figure out why, create a 'minimal' omex file that has the minimal requirements to be accepted by biosimulators.

**Comment by robertvi** [comment]
The [create_omex](https://github.com/robertvi/SBMLShowcase/blob/ff91517556b4dd5265a284b6576201a1b2e5f58e/utils/__init__.py#L44) function currently uses the [pymetadata](https://github.com/matthiaskoenig/pymetadata) module to create omex files containing the SBML and SEDML files. It also inserts a manifest entry to the omex file itself, which generates a warning from biosimulators that this is not part of the combine/omex standard. However this is not the main issue. Rather the biosimulators sedml parser throws an error about the model contents.

**Comment by stellaprins** [comment]
These are the SBML and SEDML files Ankur has successfuly used to create an omex file that Biosimulators accepts:
[SBML/LEMS_NML2_Ex9_FN.sbml](https://github.com/robertvi/SBMLShowcase/blob/ff91517556b4dd5265a284b6576201a1b2e5f58e/SBML/LEMS_NML2_Ex9_FN.sbml)
[LEMS_NML2_Ex9_FN.sedml](https://github.com/robertvi/SBMLShowcase/blob/ff91517556b4dd5265a284b6576201a1b2e5f58e/SBML/LEMS_NML2_Ex9_FN.sedml)

**Comment by robertvi** [comment]
Ok, then I'll use pymetadata module to create one using those as well, to check it also works. Do you know how he created the omex file?

**Comment by stellaprins** [comment]
I've looked at all references in the SBML Showcase to the [create_omex](https://github.com/robertvi/SBMLShowcase/blob/ff91517556b4dd5265a284b6576201a1b2e5f58e/utils/__init__.py#L44) function and it is only called in [run_biosimulators_docker](https://github.com/robertvi/SBMLShowcase/blob/384177e2187b624f5dd4105e4dd8bc3afa49eb64/utils/__init__.py#L83).

In the folder with the SBML and SEDML files Ankur used I can only find a validation of the seperate files ([validateAll.sh](https://github.com/robertvi/SBMLShowcase/blob/384177e2187b624f5dd4105e4dd8bc3afa49eb64/SBML/validateAll.sh)) but not a validation of an omex file.

I will have a look here too
[Wednesday 12:53] Sinha, Ankur
https://github.com/NeuroML/pyNeuroML/blob/development/pyneuroml/biosimulations.py#L167 -> submitting to biosimulations

**Comment by robertvi** [comment]
create_omex (pymetadata) makes an omex file, which then generates errors about the sedml variables not being in the correct namespace. Same result from uploading the omex file to biosimulators.

**Comment by stellaprins** [comment]
Quick fix in `create_omex` in `utils\__init__.py` allows us to create a minimal omex file `SBML\LEMS_NML2_Ex9_FN.omex`. 

The resulting minimal omex file `SBML\LEMS_NML2_Ex9_FN.omex`  [biosimulations tool](https://run.biosimulations.org/runs/new) was used to run simulations on https://run.biosimulations.org/
- [x] Simulator: [tellurium 2.2.8](https://biosimulators.org/simulators/tellurium) (Sensible output was produced)
- [x] Simulator: [copasi 4.42.284](https://biosimulators.org/simulators/copasi) **Failed**
- [x] Simulator: [amici 0.18.1](https://biosimulators.org/simulators/amici) (No output was produced)
- [x] Simulator: [vcell 7.5.0.127](https://biosimulators.org/simulators/vcell) (No output was produced)
- [x] Simulator: [pysces 1.2.1](https://biosimulators.org/simulators/pysces) **Failed**
- [x] Simulator: [gillespy2 1.6.6](https://biosimulators.org/simulators/gillespy2) (No sensible output was produced, flat line)
- [x] Simulator: [libsbmlsim 1.4.0](https://biosimulators.org/simulators/libsbmlsim) (Sensible output was produced)
- [x] Simulator: [masspy 0.1.6](https://biosimulators.org/simulators/masspy) **Failed**

**Comment by stellaprins** [comment]
**Simulation Run Details**

Name: test_minimal_omex_tellurium
Id: #66433e6716d2b6badabf1246
	Simulator: [tellurium 2.2.8](https://biosimulators.org/simulators/tellurium)
	CPU cores: 1
	RAM: 8 GB
	Max time: 20 m
	Submitted: 2024-05-14 11:35:20 AM
	Updated: 2024-05-14 11:35:37 AM
Status: **Succeeded**

Name: test_minimal_omex_copasi
Id: #6643403921392a553ec4f1a2
	Simulator: [copasi 4.42.284](https://biosimulators.org/simulators/copasi)
	CPU cores: 1
	RAM: 8 GB
	Max time: 20 m
	Submitted: 2024-05-14 11:43:06 AM
	Updated: 2024-05-14 11:43:23 AM
Status: **Failed**

Name: test_minimal_omex_amici
Id: #6643429507f7ec63789130fc
	Simulator: [amici 0.18.1](https://biosimulators.org/simulators/amici)
	CPU cores: 1
	RAM: 8 GB
	Max time: 20 m
	Submitted: 2024-05-14 11:53:10 AM
	Updated: 2024-05-14 11:53:54 AM
Status: **Succeeded**

Name: test_minimal_omex_virtualcell
Id: #6643424d07f7ec63789130df
	Simulator: [vcell 7.5.0.127](https://biosimulators.org/simulators/vcell)
	CPU cores: 1
	RAM: 8 GB
	Max time: 20 m
	Submitted: 2024-05-14 11:51:58 AM
	Updated: 2024-05-14 11:52:37 AM
Status: **Succeeded**

Name: test_minimal_omex_pysces
Id: #664342d821392a553ec4f1e4
	Simulator: [pysces 1.2.1](https://biosimulators.org/simulators/pysces)
	CPU cores: 1
	RAM: 8 GB
	Max time: 20 m
	Submitted: 2024-05-14 11:54:16 AM
	Updated: 2024-05-14 11:54:34 AM
Status: **Failed**

Name: test_minimal_omex_gillespy2
Id: #6643441116d2b6badabf12ec
	Simulator: [gillespy2 1.6.6](https://biosimulators.org/simulators/gillespy2)
	CPU cores: 1
	RAM: 8 GB
	Max time: 20 m
	Submitted: 2024-05-14 11:59:29 AM
	Updated: 2024-05-14 11:59:51 AM
Status: **Succeeded**

Name: test_minimal_omex_libsbmlsim
Id: #6643443507f7ec6378913148
	Simulator: [libsbmlsim 1.4.0](https://biosimulators.org/simulators/libsbmlsim)
	CPU cores: 1
	RAM: 8 GB
	Max time: 20 m
	Submitted: 2024-05-14 12:00:05 PM
	Updated: 2024-05-14 12:00:33 PM
Status: **Succeeded**

Name: test_minimal_omex_masspy
Id: #664344a816d2b6badabf1304
	Simulator: [masspy 0.1.6](https://biosimulators.org/simulators/masspy)
	CPU cores: 1
	RAM: 8 GB
	Max time: 20 m
	Submitted: 2024-05-14 12:02:00 PM
	Updated: 2024-05-14 12:02:23 PM
Status: **Failed**

**Comment by stellaprins** [comment]
Do they have a sensible output?

**Comment by robertvi** [comment]
created a new branch [here](https://github.com/robertvi/SBMLShowcase/tree/preserve_tables) to preserve the local tellurium run results tables, not yet implemented any actual changes yet, but this branch is where I will roll back to the original version of the table generation scripts to preserve the results

**Comment by robertvi** [comment]
The changes that preserve the current markdown tables have been merged into master branch on opensourcebrain repo. For now let's make sure we don't change the generator scripts (https://github.com/robertvi/SBMLShowcase/blob/master/test_suite/process_test_suite.py) and (https://github.com/robertvi/SBMLShowcase/blob/master/BioModels/parse_biomodels.py) until we have a fully tested biosimulators method for running the test suite and biomodels

**Comment by robertvi** [comment]
Am going to work using the https://github.com/robertvi/SBMLShowcase/tree/test_omex branch

**Comment by robertvi** [comment]
I fixed the output dir is the same as the input dir problem and merged the changes back into test_omex branch
