### ISSUE TITLE
 set entry format dynamically in create_omex function

### ISSUE THREAD

**Issue by stellaprins** [robertvi/SBMLShowcase#3]
[create_omex](https://github.com/robertvi/SBMLShowcase/blob/2c38d1abe0542196ed51e45f3e1f24b4c73e2e1e/utils/__init__.py#L44) function has some [hardcoded bits](https://github.com/robertvi/SBMLShowcase/blob/2c38d1abe0542196ed51e45f3e1f24b4c73e2e1e/utils/__init__.py#L72) that cause issues for running in biosimulator.

**Comment by robertvi** [comment]
create_omex needs to use libsbml to get the sbml version from the sbml file and then set the appropriate version in the omex manifest entry, something like:
```from libsbml import *
reader = SBMLReader()
doc = reader.readSBML("my_model.sbml")
ver = doc.getVersion()```

**Comment by stellaprins** [comment]
Check whether minimal omex file `SBML\LEMS_NML2_Ex9_FN.omex` is accepted using the [biosimulations tool](https://run.biosimulations.org/runs/new) on https://run.biosimulations.org/
- [ ] Simulator: [tellurium 2.2.8](https://biosimulators.org/simulators/tellurium)
- [ ] Simulator: [copasi 4.42.284](https://biosimulators.org/simulators/copasi)

**Comment by stellaprins** [comment]
**Simulation Run Details**
Name: test_minimal_omex_tellurium
Id: #66433e6716d2b6badabf1246
	Simulator: [tellurium 2.2.8](https://biosimulators.org/simulators/tellurium)
	CPU cores: 1
	RAM: 8 GB
	Max time: 20 m
	Submitted: 2024-05-14 11:35:20 AM
	Updated: 2024-05-14 11:35:37 AM
Status: **Succeeded**





**Simulation Run Details**
Name: test_minimal_omex_copasi
Id: #6643403921392a553ec4f1a2
	Simulator: [copasi 4.42.284](https://biosimulators.org/simulators/copasi)
	CPU cores: 1
	RAM: 8 GB
	Max time: 20 m
	Submitted: 2024-05-14 11:43:06 AM
	Updated: 2024-05-14 11:43:23 AM
Status: **Failed**

**Comment by stellaprins** [comment]
I've added a get_entry_format function so that entry format can be set dynamically in create_omex function. See commit [here](https://github.com/robertvi/SBMLShowcase/commit/cb60aa2cf44fc9b031c9e57182b8bc45ad0e44e2).

To double check whether the created omex file was valid I ran it on https://biosimulators.org.

**Simulation Run Details**
Name: test_minimal_omex_new_tellurium
Id: #664462d607f7ec6378913b6f
	Simulator: [tellurium 2.2.8](https://biosimulators.org/simulators/tellurium)
	CPU cores: 1
	RAM: 8 GB
	Max time: 20 m
	Submitted: 2024-05-15 08:23:03 AM
	Updated: 2024-05-15 08:23:24 AM
Status: **Succeeded**

**Comment by stellaprins** [comment]
I still get this error when I am creating the minimal omex file. The error was there too before I changed anything.

`The COMBINE/OMEX did not execute successfully: The SED document did not execute successfully:  [Errno 17] File exists: '/root/out/LEMS_NML2_Ex9_FN.sedml'`

**Comment by robertvi** [comment]
It seems that biosimulators wants to create a new directory called /root/out/LEMS_NML2_Ex9_FN.sedml in the container filesystem, which will map straight on top of the input sedml file if you try to use the same folder as the input and output directories for the docker call. In this new output folder it will put various output files. Therefore this is solved in my new branch which separates the input and output folders (https://github.com/robertvi/SBMLShowcase/tree/separate_input_output_dirs)

**Comment by robertvi** [comment]
@stellaprins should we close this issue now?
