### ISSUE TITLE
Issue 5 namespace errors need a libsedml based fix

### ISSUE THREAD

**Issue by robertvi** [robertvi/SBMLShowcase#7]
The namespace related errors in this issue are likely due to a missing namespace attribute near the top of the sedml file 
https://github.com/robertvi/SBMLShowcase/issues/5

We manually fixed this error in a single sedml file by adding the following missing attribute: 
`xmlns:sbml="http://www.sbml.org/sbml/level2/version2"` 
see [here](https://github.com/OpenSourceBrain/SBMLShowcase/commit/4847f78656dd244ddb19b6f0d2a733c1eb2664f5). 

It would probably make sense to be able to programmatically add the missing attribute using libsedml if there is a suitable library function available

**Comment by stellaprins** [comment]
to do:
- [x] check out [BioSimulators utils](https://github.com/biosimulators/Biosimulators_utils/) library for reading, writing, validating and executing SED-ML documents. A tutorial for the command-line interface is available [here](https://docs.biosimulators.org/Biosimulators_utils/).
- [x] create fix_sedml helper function for create_omex if sedml namespace is invalid

In the future: fix_sedml functionality to pynml. [This ](https://github.com/NeuroML/pyNeuroML/blob/development/pyneuroml/utils/__init__.py#L562)is the current implementation of the "get model files" to which the fix_sedml and create_omex could be eventually added.


libraries and tools working with SED-ML can be found [here]( https://sed-ml.org/showcase.html)

**Comment by stellaprins** [comment]
Can the currently set namespaces be fetched from a SED-ML file?

The [BioSimulators utils](https://github.com/biosimulators/Biosimulators_utils/) library for reading, writing, validating and executing SED-ML documents could be helpful. A tutorial for the command-line interface is available [here](https://docs.biosimulators.org/Biosimulators_utils/).

Relevant libSEDML issues:
- [Can't figure out how to add namespace in python #158 ](https://github.com/fbergmann/libSEDML/issues/158)
- [SEDBase::getNamespaces only returns the namespaces declared on the root element
#77](https://github.com/fbergmann/libSEDML/issues/77) 


Check functions `getElementNamespaces `  `getNamespaces ` and `setNamespaces` mentioned in [libSEDML issue #158 ](https://github.com/fbergmann/libSEDML/issues/158)
-  - [x] `sedml_file.getElementNamespaces()` `<libcombine.XMLNamespaces; proxy of <Swig Object of type 'XMLNamespaces *' at 0x000001F438A8E370> >`
-  - [x] `sedml_file.getNamespaces()` `<libcombine.XMLNamespaces; proxy of <Swig Object of type 'XMLNamespaces *' at 0x000001F438A8EC40> >`
-  - [x] `sedml_file.setNamespaces()`   `TypeError: SedBase.setNamespaces() missing 1 required positional argument: 'xmlns'`

**Comment by stellaprins** [comment]
To do
- [x] treat the SED-ML file as text and do a detect replace approach 
- [x] create temporary SED-ML files that are fixed (i.e. `xmlns:sbml `attribute added), and are deleted after they have been used to create an OMEX file which has been tested
